// generated by cursor + claude-3.5-sonnet
// simplified in many iterations, this wasn't how it came out.

import { parse } from '../eksitext-2024.mjs';

describe('Ekşi Sözlük Parser', () => {
  const testCases = [
    {
      name: 'simple ara',
      input: '(ara: query)',
      expected: [{ type: 'ara', query: 'query' }]
    },
    {
      name: 'wildcard ara',
      input: '(ara: at av* si*)',
      expected: [{ type: 'ara', query: 'at av* si*' }]
    },
    {
      name: 'simple gbkz',
      input: '`query`',
      expected: [{ type: 'gbkz', query: 'query' }]
    },
    {
      name: 'gbkz with spaces',
      input: '`query with spaces`',
      expected: [{ type: 'gbkz', query: 'query with spaces' }]
    },
    {
      name: 'simple bkz',
      input: '(bkz: query)',
      expected: [{ type: 'bkz', query: 'query' }]
    },
    {
      name: 'bkz with spaces',
      input: '(bkz: query with spaces)',
      expected: [{ type: 'bkz', query: 'query with spaces' }]
    },
    {
      name: 'bkz with "."',
      input: '(bkz: garantibbva.com.tr)',
      expected: [{ type: 'bkz', query: 'garantibbva.com.tr' }]
    },
    {
      name: 'bkz with "\'"',
      input: '(bkz: beşiktaş\'ın şampiyon olacağı kesin tarih)',
      expected: [{ type: 'bkz', query: 'beşiktaş\'ın şampiyon olacağı kesin tarih' }]
    },
    {
      name: 'bkz with "-"',
      input: '(bkz: covid-19)',
      expected: [{ type: 'bkz', query: 'covid-19' }]
    },
    {
      name: 'bkz with "_"',
      input: '(bkz: dondurma_id)',
      expected: [{ type: 'bkz', query: 'dondurma_id' }]
    },
    {
      name: 'bkz with "%"',
      input: '(bkz: 21 aralık 2022 mtv zammının %61 5 olması)',
      expected: [{ type: 'bkz', query: '21 aralık 2022 mtv zammının %61 5 olması' }]
    },
    {
      name: 'bkz with "+"',
      input: '(bkz: sandisk sansa clip+)',
      expected: [{ type: 'bkz', query: 'sandisk sansa clip+' }]
    },
    {
      name: 'bkz with "€"',
      input: '(bkz: 70 milyon € harcayıp kupayı gs\'ye kaybetmek)',
      expected: [{ type: 'bkz', query: '70 milyon € harcayıp kupayı gs\'ye kaybetmek' }]
    },
    {
      name: 'bkz with "/"',
      input: '(bkz: maaş/yapılan iş oranı en yüksek meslek)',
      expected: [{ type: 'bkz', query: 'maaş/yapılan iş oranı en yüksek meslek' }]
    },
    {
      name: 'bkz with "="',
      input: '(bkz: sen beni güldürdün x de seni güldürsün x=allah)',
      expected: [{ type: 'bkz', query: 'sen beni güldürdün x de seni güldürsün x=allah' }]
    },
    {
      name: 'bkz with "("',
      input: '(bkz: gibi (dizi))',
      expected: [{ type: 'bkz', query: 'gibi (dizi)' }]
    },
    {
      name: 'bkz with ")"',
      input: '(bkz: gibi (dizi))',
      expected: [{ type: 'bkz', query: 'gibi (dizi)' }]
    },
    {
      name: 'bkz with "^"',
      input: '(bkz: 10^10^10^56 yıl sonra evrenin resetlenecek olması)',
      expected: [{ type: 'bkz', query: '10^10^10^56 yıl sonra evrenin resetlenecek olması' }]
    },
    {
      name: 'bkz with "&"',
      input: '(bkz: sight & sound\'a göre 2023\'ün en iyi 50 filmi)',
      expected: [{ type: 'bkz', query: 'sight & sound\'a göre 2023\'ün en iyi 50 filmi' }]
    },
    {
      name: 'bkz with "$"',
      input: '(bkz: gri pasaport+$128 milyar+dezenfektan+pudra)',
      expected: [{ type: 'bkz', query: 'gri pasaport+$128 milyar+dezenfektan+pudra' }]
    },
    {
      name: 'bkz with "#"',
      input: '(bkz: #melihgokcektimarhaneye)',
      expected: [{ type: 'bkz', query: '#melihgokcektimarhaneye' }]
    },
    {
      name: 'abkz with visible and hidden parts',
      input: '`visible:hidden`',
      expected: [{ type: 'abkz', text: 'visible', query: 'hidden' }]
    },
    {
      name: 'abkz with only hidden part',
      input: '`:hidden`',
      expected: [{ type: 'abkz', text: null, query: 'hidden' }]
    },
    {
      name: 'direct entry query',
      input: '#123',
      expected: [{ type: 'entry_query', entry_id: '123' }]
    },
    {
      name: 'simple URL (https)',
      input: 'https://example.com',
      expected: [{ type: 'url', url: 'https://example.com' }]
    },
    {
      name: 'simple URL (http)',
      input: 'http://example.com',
      expected: [{ type: 'url', url: 'http://example.com' }]
    },
    {
      name: 'simple URL (ftp)',
      input: 'ftp://example.com',
      expected: [{ type: 'url', url: 'ftp://example.com' }]
    },
    {
      name: 'URL with port',
      input: 'http://example.com:8080',
      expected: [{ type: 'url', url: 'http://example.com:8080' }]
    },
    {
      name: 'URL with parameterless query',
      input: 'https://example.com/?',
      expected: [{ type: 'url', url: 'https://example.com/?' }]
    },
    {
      name: 'URL with Unicode hostname',
      input: 'https://ÖÇŞİĞÜöçşığü.com',
      expected: [{ type: 'url', url: 'https://ÖÇŞİĞÜöçşığü.com' }]
    },
    {
      name: 'URL with hostname containing underscore',
      input: 'https://old_style.example.com/',
      expected: [{ type: 'url', url: 'https://old_style.example.com/' }]
    },
    {
      name: 'named URL',
      input: '[https://example.com Example]',
      expected: [{ type: 'named_url', url: 'https://example.com', title: 'Example' }]
    },
    {
      name: 'unnamed URL',
      input: '[https://example.com]',
      expected: [{ type: 'url', url: 'https://example.com' }]
    },
    {
      name: 'paragraph break',
      input: 'text1\n\ntext2',
      expected: ['text1', { type: 'paragraph_break' }, 'text2']
    },
    {
      name: 'line break',
      input: 'text1\ntext2',
      expected: ['text1', { type: 'line_break' }, 'text2']
    },
    {
      name: 'mixed content',
      input: 'Hello (bkz: world). `gbkz` and [https://example.com Example] and [https://unnamed-url.tld] and #123.\n\nNew paragraph.',
      expected: [
        'Hello ',
        { type: 'bkz', query: 'world' },
        '. ',
        { type: 'gbkz', query: 'gbkz' },
        ' and ',
        { type: 'named_url', url: 'https://example.com', title: 'Example' },
        ' and ',
        { type: 'url', url: 'https://unnamed-url.tld' },
        ' and ',
        { type: 'entry_query', entry_id: '123' },
        '.',
        { type: 'paragraph_break' },
        'New paragraph.'
      ]
    },
    {
      name: 'abkz',
      input: 'herkes kötü deneyimlerimle ve duygularımla dalga geçiyor. hayatı boyunca bulunduğu -istisnasız- her yerde şiddete maruz kalmış biri olarak beni `cesaret`lendirecek birini bulmalıydım. bu yüzden ekşi sözlük her ne kadar kendisine öğretilen milyonlarca `bilgi`yi sorgularken`:sorgulamak` gerçek benliğini bulmakta',
      expected: [
        "herkes kötü deneyimlerimle ve duygularımla dalga geçiyor. hayatı boyunca bulunduğu -istisnasız- her yerde şiddete maruz kalmış biri olarak beni ",
        {
          "query": "cesaret",
          "type": "gbkz"
        },
        "lendirecek birini bulmalıydım. bu yüzden ekşi sözlük her ne kadar kendisine öğretilen milyonlarca ",
        {
          "query": "bilgi",
          "type": "gbkz"
        },
        "yi sorgularken",
        {
          "query": "sorgulamak",
          "text": null,
          "type": "abkz"
        },
        " gerçek benliğini bulmakta"
      ]
    }
  ];
  testCases.forEach(({ name, input, expected }) => {
    it(`should parse ${name} correctly`, () => {
      const result = parse(input);
      expect(result).toEqual(expected);
    });
  });
});